### ISSUE TITLE
关于该程序的一个bug

### ISSUE THREAD

**Issue by KevinStigma** [anydream/Pmx2Fbx#1]
我下载了这个仓库，发现你的代码中有这么一段：
`// 设置透明通道
			FbxFileTexture * pFbxOpacityTex = fbx.NewTexture("Opacity", currMat.Tex.c_str());
			pFbxOpacityTex->SetAlphaSource(FbxTexture::eBlack);
			pFbxMat->TransparentColor.ConnectSrcObject(pFbxOpacityTex);
			shp->AddMaterial(pFbxMat);`
用你的代码导出的fbx文件，透明度明显有问题，我怀疑是这段代码的问题。因为这里不能贴图，所以没法用图来说明。能否留一个联系方式呢？我想和你深入探讨一下这个问题。

**Comment by anydream** [comment]
试试把里面的 MonoOutput.ms 脚本拖进 3dsMax？
