### ISSUE TITLE
How to assign a material address when converting

### ISSUE THREAD

**Issue by zehuichen123** [anydream/Pmx2Fbx#2]
I've successfully convert my .pmx file to .fbx format, but the material was not properly loaded together with the model. Thus, only gray model was shown when I open my .fbx file. So if can I add  a parameter to assign an address when converting or just move my material files to someplace so that those files can be automatically loaded? Thanks!

**Comment by anydream** [comment]
Maybe the maxscript "MonoOutput.ms" can help you to solve this problem. I can't remember the details, sorry for my forget :P

**Comment by zehuichen123** [comment]
Ok~ , but how can I run `MonoOutput.ms` ? I only download Pmx2Fbx.exe and run it before. Should I download the whole project and compile it myself ?  And then how can I use `MonoOutput.ms`? I am not good at this, can you give me some advice ? Thanks

**Comment by anydream** [comment]
你可以搜一下3dsMax如何运行maxscript，我记得有专门的菜单项。

**Comment by zehuichen123** [comment]
嗷 好的 谢谢啦～
