### ISSUE TITLE
关于vmd

### ISSUE THREAD

**Issue by chenloveheimei** [anydream/Pmx2Fbx#3]
你好,我叫龙.看到你写的是中国,应该是中国人吧.
问题:现在pmx或者pmd转成fbx,只是模型,但是如果再想加入vmd的骨骼动画的话呢,可以实现的吗?能否提供一些ideas.
谢谢啦!

**Comment by anydream** [comment]
这个项目是多年前写的，现在很多细节已经记不清了。
印象中网上有不少vmd转fbx的工具，你可以试一下。

**Comment by chenloveheimei** [comment]
好的,我去了解下.谢谢.
